

- name: Setup MySQL Setup
  hosts: all
  become: true
  tasks:
    - name: Disable the MYSQL Default version
      ansible.builtin.shell: dnf module disable mysql -y

    - name: Copy mysql repo content
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: installed

    - name: Start MySQL Service
      ansible.builtin.systemd_service:
        name: mysqld
        state: restarted

    - name: Set MySQL Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1